#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MathFighter.Resource", IsApplication=true)]

namespace MathFighter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int backgroundspinner = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int answer = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int layout_columns = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int listView_top_player_highscores = 2131165202;
			
			// aapt resource value: 0x7f070007
			public const int main_btn_difficulty = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int main_btn_highscore = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int main_btn_start = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int main_btn_topics = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int main_txt_topics = 2131165190;
			
			// aapt resource value: 0x7f070013
			public const int new_highscore_name = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int new_highscore_ok_btn = 2131165204;
			
			// aapt resource value: 0x7f07000a
			public const int question = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int quiz_btn_answer = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int rb_gangetabellen = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int rb_kvadratrot = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int rb_lett_blanding = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int rbg_tema = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int rocklion_presents = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int status = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int subject_gangetabellenBtn = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int subject_questionsToggle = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int subject_questionsToggleLabel = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int tv_player = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int tv_playtime = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int tv_position = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int tv_score = 2131165207;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar_top_player = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_quiz = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_subject = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_top_player = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_new_highscore = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_highscore = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int correct = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int incorrect = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
